name: Require “Allow Edits”

on: [pull_request_target]

jobs:
  _:
    name: "Require “Allow Edits”"

    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@main
    - uses: ljharb/require-allow-edits@main
